public class SalesforceDeveloper {
    public  void  myFirstCode() {
        string sehir ='izmir';
        string film ='BreakingBad';
        string season ='Spring';
        system.debug('My favourite '+ sehir + film + season + 'dir.');

    }

    public void myFavorites(string a, integer b){
        
        string mySehr = a;
        integer myNum = b;
        string myt = a+ ' '+ b;
        system.debug('my favourite is '+ myt);
        
      


    }
}
