conditionclass_assignment mq = new conditionclass_assignment();
string vk = mq.classmethod(1);
system.debug(vk);
string ab= mq.classmethod(2);
system.debug(ab);
string cd = mq.classmethod(15);
system.debug(cd);
string df = mq.Quarter('January');
system.debug(df);
string ef = mq.Quarter('may');
system.debug(ef);
string gh = mq.Quarter('February');
system.debug(gh);


/*system.debug(mq.classmethod(1));
string vk = mq.classmethod(1);
system.debug(vk);*/

